"""Glue between the agent and the runner: run a natural-language case (or a single `agent` step), and turn the outcome into
normal testbot results (one step per agent action, with screenshots), a reasoning trace file and a generated script."""
from __future__ import annotations

import json
import re
import time
from pathlib import Path
from typing import Any, Optional
from urllib.parse import urlsplit

from framework import logs
from framework.agent.config import AgentConfig, Profile
from framework.agent.loop import AgentOutcome, AgentRun
from framework.agent.policy import is_secret_name
from framework.models import CaseResult, StepResult, TestCase, TestStep, TestSuite
from framework.variables.context import VariableContext

log = logs.get("agent")
_VAR = re.compile(r"\{([A-Za-z_]\w*)\}")


def load_profile(cfg: AgentConfig) -> Profile:
    if not cfg.profile:
        return Profile()
    path = Path(cfg.profile)
    if not path.exists():
        from framework.cli import app_root

        path = app_root() / cfg.profile
    return Profile.load(str(path))


def _data_used(rec) -> str:
    bits = [f"{k}={v}" for k, v in rec.args.items() if k not in ("covers", "data_source") and v not in (None, "")]
    return ", ".join(str(b)[:140] for b in bits)


def _trace_dict(outcome: AgentOutcome, objective: str, expect: list[str]) -> dict[str, Any]:
    return {
        "objective": objective, "expect": expect, "verdict": outcome.verdict.status, "reason": outcome.verdict.reason,
        "downgraded_from": outcome.verdict.downgraded_from, "ai_judgement_only": outcome.verdict.ai_judgement, "summary": outcome.summary,
        "usage": {"model_turns": outcome.turns, "tokens_in": outcome.tokens_in, "tokens_out": outcome.tokens_out, "seconds": outcome.seconds},
        "data_decisions": outcome.data_log, "notes": outcome.notes, "outcomes_claimed": outcome.verdict.outcomes, "profile": outcome.profile_name,
        "actions": [{"n": r.n, "tool": r.tool, "args": r.args, "reason": r.reason, "ok": r.ok, "status": r.status, "message": r.message,
                     "screenshot": r.shot, "assertion": r.assertion} for r in outcome.records],
    }


def write_trace(run_dir: Path, name: str, outcome: AgentOutcome, objective: str, expect: list[str]) -> str:
    folder = run_dir / "agent-traces"
    folder.mkdir(parents=True, exist_ok=True)
    path = folder / f"{re.sub(r'[^A-Za-z0-9_.-]+', '_', name)}.json"
    path.write_text(json.dumps(_trace_dict(outcome, objective, expect), indent=2, ensure_ascii=False, default=str), encoding="utf-8")
    return path.relative_to(run_dir.parent).as_posix() if run_dir.parent in path.parents else str(path)


def generated_suite(outcome: AgentOutcome, suite: Optional[TestSuite], case: TestCase, ctx: VariableContext, base_url: str) -> dict[str, Any]:
    run_id = str(ctx.as_dict().get("run_id", ""))
    names: set[str] = set()

    def clean(value: Any) -> Any:
        if isinstance(value, str):
            if run_id and run_id in value:
                value = value.replace(run_id, "{run_id}")
            names.update(_VAR.findall(value))
            return value
        if isinstance(value, dict):
            return {k: clean(v) for k, v in value.items()}
        if isinstance(value, list):
            return [clean(v) for v in value]
        return value

    steps = []
    for i, step in enumerate(outcome.export_steps, start=1):
        s = clean(json.loads(json.dumps(step)))
        steps.append({"step_no": i, **s})
    variables: dict[str, Any] = {}
    known = {**(suite.variables if suite else {}), **case.variables}
    current = ctx.as_dict()
    for name in sorted(names - {"base_url", "worker_id", "iteration"}):
        if name == "run_id":
            variables[name] = {"source": "faker", "type": "bothify", "pattern": "##########"}
        elif is_secret_name(name):      # secrets are NEVER written into a generated script, even if the suite defines them
            variables[name] = {"source": "constant", "value": "CHANGE_ME"}
        elif name in known:
            variables[name] = known[name].model_dump(exclude_none=True)
        else:
            variables[name] = {"source": "constant", "value": str(current.get(name, ""))}
    doc: dict[str, Any] = {"suite_id": f"{suite.suite_id if suite else 'AGENT'}-{case.id}-AGENT", "suite_name": f"{case.title} (generated by the agent)"}
    if base_url:
        doc["base_url"] = base_url
    if variables:
        doc["variables"] = variables
    doc["cases"] = [{"id": case.id, "title": case.title, "preconditions": "Generated from an agent run. Review the steps and checks before relying on it.", "steps": steps}]
    TestSuite.model_validate(doc)   # what we write is something the runner can load
    return doc


def _model_name(cfg: AgentConfig) -> str:
    return f"{cfg.provider}:{cfg.model or 'default'}"


def run_agent_case(orch: Any, page: Any, case: TestCase, ctx: VariableContext, screenshot_id: str, suite: Optional[TestSuite], agent_overrides: Optional[dict[str, Any]]) -> CaseResult:
    started = time.monotonic()
    cfg = AgentConfig.from_env({**(suite.agent if suite and suite.agent else {}), **(agent_overrides or {}), **(case.agent or {})})
    profile = load_profile(cfg)
    base_url = str(ctx.as_dict().get("base_url", ""))
    start_url = ctx.resolve_string(case.start_url) if case.start_url else ""
    run = AgentRun(page, objective=ctx.resolve_string(case.objective or ""), data_hints=case.data_hints or "", expect=case.expect, constraints=case.constraints,
                   start_url=start_url, base_url=base_url, ctx=ctx, sql_conns=orch.sql_connections, cfg=cfg, profile=profile,
                   shot=lambda n, status: orch._capture_screenshot(page, screenshot_id, n, status))
    run.watch.host = urlsplit(base_url).netloc
    log.info("case %s: agent started (%s, up to %d actions, %d s, profile=%s)", case.id, _model_name(cfg), cfg.max_steps, cfg.timeout_s, profile.name or "none")
    log.debug("case %s objective: %s", case.id, logs.clip(run.objective, 600))
    outcome = run.run()
    log.log(20 if outcome.verdict.status == "pass" else (40 if outcome.verdict.status == "error" else 30),
            "case %s: agent verdict %s -- %s (%d model turn(s), %d tokens in / %d out, %.0f s)", case.id, outcome.verdict.status.upper(),
            logs.clip(outcome.verdict.reason, 300), outcome.turns, outcome.tokens_in, outcome.tokens_out, outcome.seconds)
    steps: list[StepResult] = []
    for rec in outcome.records:
        a = rec.assertion
        steps.append(StepResult(
            step_no=rec.n, description=(f"{rec.tool}: {rec.message}" if not a else f"check {a['kind']} ({a['id']})") + (f"  -- {rec.reason[:140]}" if rec.reason else ""),
            action=f"agent:{rec.tool}", data_used=_data_used(rec) or None,
            status=("pass" if rec.ok and (a is None or a["passed"]) else ("fail" if a and not a["passed"] else "skipped")),
            actual=a["actual"] if a else None, expected=a["expected"] if a else None, error=None if rec.ok else rec.message,
            screenshot_path=rec.shot, duration_ms=rec.duration_ms))
    trace_path = write_trace(Path(orch._run_dir), case.id, outcome, case.objective or "", case.expect)
    script_note = ""
    try:
        if outcome.export_steps:
            folder = Path(orch._run_dir) / "agent-generated"
            folder.mkdir(parents=True, exist_ok=True)
            doc = generated_suite(outcome, suite, case, ctx, base_url)
            gp = folder / f"{re.sub(r'[^A-Za-z0-9_.-]+', '_', case.id)}.json"
            gp.write_text(json.dumps(doc, indent=2, ensure_ascii=False), encoding="utf-8")
            script_note = f" | generated script: {gp.relative_to(Path(orch._run_dir).parent).as_posix()}"
    except Exception as exc:  # noqa: BLE001 - export problems never change the verdict
        script_note = f" | script export failed: {exc}"
    v = outcome.verdict
    data = "; ".join(f"{d['field']}={d['value']} ({d['source']})" for d in outcome.data_log) or "none"
    steps.append(StepResult(
        step_no=len(steps) + 1, description=f"Agent verdict: {v.reason}" + (" [AI judgement only]" if v.ai_judgement else ""), action="agent:verdict",
        data_used=(f"model {_model_name(cfg)} | {outcome.turns} turns, {outcome.tokens_in}+{outcome.tokens_out} tokens, {outcome.seconds}s | data decisions: {data} | trace: {trace_path}{script_note}"),
        status=v.status, actual=outcome.summary or None, expected=case.expect or None, error=None if v.status == "pass" else v.reason,
        screenshot_path=orch._capture_screenshot(page, screenshot_id, len(steps) + 1, v.status), duration_ms=int(outcome.seconds * 1000)))
    return CaseResult(case_id=case.id, title=case.title, status=v.status, steps=steps, duration_ms=int((time.monotonic() - started) * 1000))


def run_agent_step(orch: Any, page: Any, step: TestStep, ctx: VariableContext, case_id: str, suite: Optional[TestSuite]) -> StepResult:
    """A single natural-language step inside an otherwise scripted test (`action: agent`, instruction in `input`)."""
    started = time.monotonic()
    conf = step.config or {}
    cfg = AgentConfig.from_env({**(suite.agent if suite and suite.agent else {}), **{k: v for k, v in conf.items() if k in ("max_steps", "vision", "allow_destructive", "timeout_s")}})
    profile = load_profile(cfg)
    base_url = str(ctx.as_dict().get("base_url", ""))
    screenshot_id = f"{case_id}_agent{step.step_no}"
    run = AgentRun(page, objective=ctx.resolve_string(step.input or ""), data_hints=str(conf.get("data_hints", "")), expect=list(conf.get("expect", [])),
                   constraints=list(conf.get("constraints", [])), start_url="", base_url=base_url, ctx=ctx, sql_conns=orch.sql_connections, cfg=cfg, profile=profile,
                   shot=lambda n, status: orch._capture_screenshot(page, screenshot_id, n, status))
    run.watch.host = urlsplit(base_url).netloc
    outcome = run.run()
    v = outcome.verdict
    trace_path = write_trace(Path(orch._run_dir), f"{case_id}_step{step.step_no}", outcome, step.input or "", list(conf.get("expect", [])))
    data = "; ".join(f"{d['field']}={d['value']}" for d in outcome.data_log) or "none"
    return StepResult(step_no=step.step_no, description=step.description, action="agent", status=v.status,
                      data_used=f"{len(outcome.records)} actions, {outcome.tokens_in}+{outcome.tokens_out} tokens | data: {data} | trace: {trace_path}",
                      actual=outcome.summary or None, error=None if v.status == "pass" else v.reason,
                      screenshot_path=orch._capture_screenshot(page, screenshot_id, 99, v.status), duration_ms=int((time.monotonic() - started) * 1000))
